### ISSUE TITLE
Parser in invalid state at byte 101

### ISSUE THREAD

**Issue by arranlomas** [arranlomas/Trickl#13]
Occurs for some users, I am having trouble replicating. This is a priority

**Comment by arranlomas** [comment]
Haven't fixed the core issue of torrent files getting into and invalid state. It seems when writing the torrent info to the working directory that it becomes invalid. Confluence served the correct file. This has been patched so the app is recoverable and torrents are still returned from getAllTorrents in confluence-wrapper. By automatically deleting corrupt torrent files and trying to redownload them

**Comment by anacrolix** [comment]
Do you have a copy of the error message?

**Comment by arranlomas** [comment]
There is no error message. Confluence just seems to not write anything past 100 Bytes. The error here (parser in invalid state) Is thrown by my torrent parser

**Comment by anacrolix** [comment]
I'm pretty certain there's a bug somewhere in confluence or torrent that is causing this. I haven't tracked it down.
