### ISSUE TITLE
Can i create my own app using Android Studio using this?

### ISSUE THREAD

**Issue by HashHackerAds** [arranlomas/Trickl#25]

**Comment by arranlomas** [comment]
Yes. Just clone the repo and open it with Android studio. At the moment you will have to change some files. Please see this issue https://github.com/arranlomas/Trickl/issues/23. 
At the moment you will have to compile confluence and torrent using gomobile bind and import the aar file into the project. I will add these to the got repo when I get home from holiday, this will make the process easier. I will close this issue when I have done that

**Comment by arranlomas** [comment]
@HashHackerAds I have updated so hopefully the instructions are a bit clearer, if your still unsure let me know here
